### ISSUE TITLE
Does rimraf 2.3.0 have issues removing files?

### ISSUE THREAD

**Issue by evs-chris** [Rich-Harris/sander#1]
On linux using gobble to build ractive, changing a file results in an ENOTEMPTY for merge steps. This started after I grabbed a fresh batch of node_modules for build changes, and I noted that there is a very new version of rimraf. Dropping back to 2.2.8 seems to resolve the issue. Is it a problem with rimraf, or have I finally slipped into the sweet embrace of insanity? Today seems to be the day for tears flowing from upstream. Now all I need is for a zebra to call me Kevin.

**Comment by Rich-Harris** [comment]
Huh. Is fine for me on OS X... can you isolate it any further, or reproduce it without all the gobble/ractive gubbins? Might be one for the rimraf issue tracker.

**Comment by evs-chris** [comment]
It is a bug in glob (isaacs/node-glob#170) that is causing problems in rimraf (isaacs/rimraf#65) when there are broken symlinks left lying about. It's odd that it doesn't seem to affect OS X. I was able to reproduce with

``` sh
cd ~
mkdir showmebug
cd showmebug
npm i rimraf
mkdir foo
ln -s ~/does/not/exist foo/nope
node_modules/.bin/rimraf foo
```

I'll close this thought, as it's a confirmed upstream issue.

**Comment by Rich-Harris** [comment]
Amazing sleuthing! Thanks. I guess the only remaining question is whether those broken symlinks are a symptom of a bug in gobble, though if that is the case then at least it turns out we're in good company! (Broccoli, in its ember-cli incarnation, was hit with the same bug.) It can remain a mystery for the time being though

**Comment by evs-chris** [comment]
It's definitely not gobble's fault. It's just a function of cleaning up output dirs when the input changes. I suppose you could work around it by cleaning out all of the downstream output dirs first, but that seems quite unnecessary. It should be perfectly valid to have a broken symlink in a folder and have that symlink removed on an `rm -rf`. Adding three lines of code to rimraf easily hacks 'round the problem. The extra neat thing is that it looks like this bug was introduced for linux when trying to work around wackiness with Windows and SunOS filesystems :)

**Comment by isaacs** [comment]
Can you please confirm that using rimraf 2.3.1 (just released) fixes this issue?

Thanks.

**Comment by evs-chris** [comment]
It does indeed! :+1:
