### ISSUE TITLE
No `appendFile` or `appendFileSync` methods

### ISSUE THREAD

**Issue by msegado** [Rich-Harris/sander#2]
Looks like `sander.appendFile` and `sander.appendFileSync` are both undefined.

(Thanks for your work on this and Gobble, btw.)

**Comment by Rich-Harris** [comment]
Thanks - weird, wonder how I missed that. Fixed in 0.2.4.

> (Thanks for your work on this and Gobble, btw.)

You're welcome! Glad they're useful
